// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuULhZ1-6fAzZLIU9OsHlSNpyuL1EEcDg',
    appId: '1:33146311171:web:2bae6e5bd94f1e76aab436',
    messagingSenderId: '33146311171',
    projectId: 'inventoryapp-1ce26',
    authDomain: 'inventoryapp-1ce26.firebaseapp.com',
    storageBucket: 'inventoryapp-1ce26.appspot.com',
    measurementId: 'G-EQ63J69YTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqdQ7amfA5OkEM8HXITNC7VVpmvYuTFfU',
    appId: '1:33146311171:android:b0d1b3da5b8fb458aab436',
    messagingSenderId: '33146311171',
    projectId: 'inventoryapp-1ce26',
    storageBucket: 'inventoryapp-1ce26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP_Sb3fBSHlYeCIkpU8Vqwt0fst3Dlhro',
    appId: '1:33146311171:ios:78c024fb12a137e8aab436',
    messagingSenderId: '33146311171',
    projectId: 'inventoryapp-1ce26',
    storageBucket: 'inventoryapp-1ce26.appspot.com',
    iosClientId: '33146311171-dttsup1ugdq8uoilpchbi1ta0gffju1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.DannysinventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP_Sb3fBSHlYeCIkpU8Vqwt0fst3Dlhro',
    appId: '1:33146311171:ios:93eedbdcc6c5c64baab436',
    messagingSenderId: '33146311171',
    projectId: 'inventoryapp-1ce26',
    storageBucket: 'inventoryapp-1ce26.appspot.com',
    iosClientId: '33146311171-46qgm9bda9ti4us6gfht51egcaf63b1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryApp.RunnerTests',
  );
}
